# Hugo global config file
# More info: https://gohugo.io/getting-started/configuration/

# Hostname (and path) to the root, e.g. https://bep.is/
baseURL: "https://skellet0r.github.io/Curriculum/"
# The site’s language code. It is used in the default RSS template and can be useful for multi-lingual sites.
languageCode: en-US
# Content without language indicator will default to this language.
defaultContentLanguage: en
# Site title
title: Ethereum Developer Curriculum
# Theme to use (located by default in /themes/THEMENAME/)
theme: hugo-theme-learn
# Render the default content language in subdir, e.g. content/en/. The site root / will then redirect to /en/.
defaultContentLanguageInSubdir: false
params:
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page.
  # Useful to give opportunity to people to create merge request for your doc.
  editURL: "https://github.com/EthBuilders/Curriculum/edit/master/content/"
  # Author of the site, will be used in meta information
  author: "EthBuilders"
  # Description of the site, will be used in meta information
  description: "Curriculum for learning to build distributed applications on the Ethereum VM"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks: false
  # Disable search function. It will hide search bar
  disableSearch: false
  # Javascript and CSS cache are automatically busted when new version of site is generated.
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting: false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard: false
  # A title for shortcuts in menu is set by default. Set this to true to disable it.
  disableShortcutsTitle: false
  # If set to false, a Home button will appear below the search bar on the menu.
  # It is redirecting to the landing page of the current language if specified. (Default is "/")
  disableLandingPageButton: true
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton: true
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb: true
  # If set to true, prevents Hugo from including the mermaid module if not needed (will reduce load times and traffic)
  # https://mermaid-js.github.io/mermaid/
  disableMermaid: true
  # Specifies the remote location of the mermaid js
  customMermaidURL: "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev: true
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby: weight
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant: "blue"
  # Provide a list of custom css files to load relative from the `static/` folder in the site root.
  # custom_css:
  #   - css/foo.css
  #   - css/bar.css
  # Change the title separator. Default to "::".
  titleSeparator: "-"
# The hugo-theme-learn uses the last improvement available in hugo version 20+ to generate a json index file ready to be consumed by lunr.js javascript search engine.
# Lunr.js is a small, full-text search library for use in the browser. It indexes JSON documents and provides a simple search interface for retrieving documents that best match text queries.
# https://lunrjs.com/
outputs:
  home:
    - HTML
    - RSS
    - JSON
# Sidebar menu configuration
menu:
  # font awesome library is included, allowing icons to be rendered
  # More info: https://learn.netlify.app/en/cont/icons/
  shortcuts:
    - name: <i class='fab fa-fw fa-github'></i> Source Code
      identifier: ds
      url: "https://github.com/EthBuilders/Curriculum"
      weight: 10
    - name: <i class="fab fa-fw fa-meetup"></i> Meetup
      identifier: meetup
      url: "https://www.meetup.com/ethbuilders/"
      weight: 11
# Example for structuring multiple lanugage support
# More info: https://learn.netlify.app/en/cont/menushortcuts/ & https://learn.netlify.app/en/cont/i18n/
# Languages:
#   en:
#     title: Documentation for Hugo Learn Theme
#     weight: 1
#     languageName: English
#     landingPageURL: /en
#     landingPageName: <i class='fas fa-home'></i> Home
#     menu:
#       shortcuts:
#         - name: <i class='fab fa-fw fa-github'></i> GitHub repo
#           identifier: ds
#           url: "https://github.com/matcornic/hugo-theme-learn"
#           weight: 10
#         - name: <i class='fas fa-fw fa-camera'></i> Showcases
#           url: showcase
#           weight: 11
#         - name: <i class='fas fa-fw fa-bookmark'></i> Hugo Documentation
#           identifier: hugodoc
#           url: "https://gohugo.io/"
#           weight: 20
#         - name: <i class='fas fa-fw fa-bullhorn'></i> Credits
#           url: /credits
#           weight: 30
